permalink: /:categories/:title/
url: "https://xiaohuansun.github.io"
full_name: “Xiaohuan”
first_name: "A big dream comes true..."
last_name: ""
blog_title: "Title"
author_img_name_path: "/images/users/user.jpg"
disqus_shortname: "example"
copyright_year: "2016"
google_analytics_code: ""
aboutme: “pretend to be cool.”
